# Generated by Django 5.2.12 on 2026-03-18 00:43

import board.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('subject', models.CharField(max_length=80, verbose_name='Matéria')),
                ('task_type', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade', 'Atividade'), ('apresentacao', 'Apresentação'), ('estudo', 'Estudo')], max_length=20, verbose_name='Tipo')),
                ('due_date', models.DateField(verbose_name='Data')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Item')),
                ('is_done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='board.task')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['is_done', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('school_name', models.CharField(blank=True, max_length=120, verbose_name='Escola')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('workspace_type', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo'), ('turma', 'Turma')], default='turma', max_length=20, verbose_name='Tipo')),
                ('invite_code', models.CharField(default=board.models.generate_invite_code, max_length=12, unique=True, verbose_name='Código de convite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.workspace'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='board.workspace')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['workspace', 'role', 'user__first_name', 'user__username'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
